name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with Ruff
      run: ruff check src tests
    - name: Test with pytest
      run: pytest tests

  deploy:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ec2-user
        SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        echo "$SSH_KEY" > key.pem
        chmod 400 key.pem
        rsync -avz -e "ssh -i key.pem" --exclude 'data/*.parquet' --exclude '.git' . $EC2_USER@$EC2_HOST:~/homerun-insights
        ssh -i key.pem $EC2_USER@$EC2_HOST "cd ~/homerun-insights && make install && sudo systemctl restart homerun-insights"
        rm key.pem
