name: CI/CD Learning Pipeline
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run linting
        run: ruff check src tests
      - name: Mock tests
        run: |
          echo "Running pytest (mocked)"
          echo "Tests passed successfully!"
  deploy:
    needs: ci
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Mock deploy to EC2
        run: |
          echo "Starting deployment to EC2 (mocked)"
          echo "Copying files to EC2 (simulated)"
          echo "Restarting application on EC2 (simulated)"
          echo "Deployment complete!"
